# Generated by Django 4.0.5 on 2023-05-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserIdentity', '0003_alter_userprofile_role_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserRole',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='user_id',
            new_name='role_id',
        ),
    ]
