# Generated by Django 4.0.5 on 2023-05-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserIdentity', '0004_rename_userprofile_userrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='description',
            field=models.TextField(),
        ),
    ]
