# Generated by Django 4.0.5 on 2023-06-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserIdentity', '0006_assignrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='id',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
