# Generated by Django 4.0.5 on 2023-05-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileStorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='remarks',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
