# Generated by Django 4.0.5 on 2023-05-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileStorage', '0003_remove_upload_id_upload_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='file_id',
        ),
        migrations.AddField(
            model_name='upload',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
